### ISSUE TITLE
Startup guide / meeting for an overview?

### ISSUE THREAD

**Issue by Kn0tas** [Bjogert/FireBanReplit#2]
I have checked through the code and I think we should have a small meeting where you show me the ropes.

**Comment by Bjogert** [comment]
I think you are correct. We should most certainly set up a small meeting and discuss this over a cup of coffee and a biscuit.

**Comment by Bjogert** [comment]
### Problem Explanation

The problem you're encountering is that the `App.css` file isn't being included in the build process when you run `npm run build`, even though it works fine during development (`npm run dev`). This can result in a white page or unstyled content in the production build. This issue typically arises due to a misconfiguration in the build process, incorrect file paths, or problems with the CSS processing setup in your build tool.

### Steps to Start Testing for Solutions

1. **Verify `App.css` File Path and Import:**
   - Ensure the import statement in your React component (e.g., `FireBanChecker.jsx`) correctly points to the `App.css` file.
   - Double-check the file path and ensure there are no typos.

2. **Check Build Configuration:**
   - Review your `vite.config.js` file to ensure it is configured to process CSS files correctly.
   - Make sure you have included the necessary plugins and options for CSS processing.

3. **Inspect the Output Directory:**
   - After running `npm run build`, manually check the `dist` directory to verify if `App.css` is present and properly referenced in `index.html`.
   - Look for any CSS files in the `dist/assets` directory and check if they are linked correctly in the output HTML.

4. **Clean and Reinstall Dependencies:**
   - Sometimes, issues can arise from corrupted or outdated dependencies. Remove the `node_modules` and `dist` directories, and delete the `package-lock.json` file.
   - Reinstall all dependencies and rebuild the project to ensure a clean setup.

5. **Check the Console and Build Logs:**
   - Look at the terminal output and build logs for any warnings or errors related to CSS processing.
   - Pay attention to any messages indicating missing files or issues with the CSS syntax.

### Example Workflow

1. **Verify File Path:**
   - Open `src/components/FireBanChecker.jsx` and ensure the import statement is correct:
     ```
     import '../App.css';
     ```

2. **Check `vite.config.js`:**
   - Ensure your `vite.config.js` includes the necessary configurations for CSS:
     ```
     import { defineConfig } from 'vite';
     import react from '@vitejs/plugin-react';

     export default defineConfig({
       plugins: [react()],
       css: {
         preprocessorOptions: {
           css: {
             // Ensure Vite processes CSS files correctly
           },
         },
       },
     });
     ```

3. **Run Build Command and Inspect Output:**
   - Run `npm run build` and check the `dist` directory:
     ```
     cd dist
     ls
     cat index.html
     ```

4. **Clean and Reinstall Dependencies:**
   - Run the following commands:
     ```
     rm -rf node_modules dist package-lock.json
     npm install
     npm run build
     ```

5. **Check for Errors and Warnings:**
   - Observe the output in the terminal for any indications of what might be causing the issue.

By following these steps methodically, you can identify and resolve the issue preventing `App.css` from being included in the production build.
